### ISSUE TITLE
tradingview

### ISSUE THREAD

**Issue by Zergity** [derion-io/trade-comp#97]

**Comment by Zergity** [comment]
1. remove currency search

![Image](https://github.com/derivable-labs/exposure-comp/assets/37166829/c534099c-1bd8-4955-ad01-e75feba6ef36)

**Comment by Zergity** [comment]
2. marker HTML

![Image](https://github.com/derivable-labs/exposure-comp/assets/37166829/5876a907-2a36-4e68-99ae-d3fa321dce50)

**Comment by Zergity** [comment]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'timeMs')
    at v.indexOfTime (library.847f247511d3f9997d72.js:127:707)
    at E.isTimeScaleExtendedTo (library.847f247511d3f9997d72.js:135:2315)
    at JSServer.ChartApi.setVisibleTimeRange (library.847f247511d3f9997d72.js:36:412)
    at ri.setVisibleTimeRange (library.847f247511d3f9997d72.js:294:2659)
    at e.exports.ChartWidget.setVisibleTimeRange (library.847f247511d3f9997d72.js:300:1150)
    at library.847f247511d3f9997d72.js:233:2203
    at new Promise (<anonymous>)
    at R.setVisibleRange (library.847f247511d3f9997d72.js:233:2168)
    at e.<anonymous> (index.tsx:119:14)
    at charting_library.esm.js:1:10306
